### ISSUE TITLE
error on run script

### ISSUE THREAD

**Issue by coneycalifornia** [ELHARAKA/BulkTRX#1]
Traceback (most recent call last):
  File "/home/kali/BulkTRX/BulkTRX.py", line 13, in <module>
    from tronapi import Tron
  File "/home/kali/.local/lib/python3.11/site-packages/tronapi/__init__.py", line 12, in <module>
    from tronapi.providers.http import HttpProvider  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/tronapi/providers/http.py", line 27, in <module>
    from tronapi.common.encoding import to_text
  File "/home/kali/.local/lib/python3.11/site-packages/tronapi/common/encoding.py", line 5, in <module>
    from eth_account.datastructures import AttributeDict
ImportError: cannot import name 'AttributeDict' from 'eth_account.datastructures' (/home/kali/.local/lib/python3.11/site-packages/eth_account/datastructures.py)

**Comment by ELHARAKA** [comment]
The error you're encountering is not related to the BulkTRX tool itself but rather to a compatibility issue with the eth_account library. The tool works correctly with eth_account version 0.11.2.

Please ensure you have this version installed by running the following command:

`pip install eth-account==0.11.2`

This should resolve the import error you are experiencing.
